[package]
name = "crocheteer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
pretty_assertions = "1.4.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_derive = "1.0.196"
serde_json = "1.0.113"
serde_yaml = "0.9.31"
stl_io = "0.7.0"
structopt = "0.3.26"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21.0"
futures-util = "0.3"
pin-utils = "0.1.0"
