[package]
name = "crochet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
pretty_assertions = "1.4.0"
stl_io = "0.7.0"
