[package]
name = "crocheteer"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sanity"]
sanity = []

[dependencies]
nalgebra = { version = "0.32.3", features = ["serde-serialize"] }
pretty_assertions = "1.4.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_derive = "1.0.196"
serde_json = "1.0.113"
serde_yaml = "0.9.31"
stl_io = "0.7.0"
structopt = "0.3.26"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21.0"
futures-util = "0.3"
pin-utils = "0.1.0"
serde-lexpr = "0.1.3"
rand = "0.7"
rand_derive = "0.5.0"
env_logger = "0.11.2"
num-traits = "0.2"
strum = "0.26.1"
strum_macros = "0.26.1"
log = "0.4.20"
num-derive = "0.4.2"
pest = "2.7.8"
pest_derive = "2.7.8"
rstar = "0.12.0"
rocket = { version = "0.5.1", features = ["json"] }
keepawake = "0.5.1"
futures = "0.3.30"
